on:
  release:
    types: [created, edited]

jobs:
  release_windows:
    runs-on: ubuntu-latest
    steps:
      - name: download widows
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: platformer.zip
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: release windows
        uses: olliemjames97/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: windows
          ITCH_GAME: plague
          ITCH_USER: dsaltares
          PACKAGE: plague-windows.zip
